### ISSUE TITLE
Code in header files

### ISSUE THREAD

**Issue by mackthehobbit** [jv110/PocketRed#3]
The headers for tiles, GUI and entities (CommandTile, PistonTile) all contain function definitions rather than just declarations, despite being marked as header files (*.h). This setup is incorrect and should be fixed; there needs to be an include-able header file, as well as a C++ source file for compilation.

**Comment by jv110** [comment]
Really? What's the problem with code in headers?

**Comment by mackthehobbit** [comment]
Because that's not what header files are for. If you include those headers from multiple source files, each will attempt to redefine the symbols: which will cause the linker to fail during the build process. It works at the moment because there is only one source file in the project (main.cpp).

**Comment by CrazyWolfy23** [comment]
Ill see what I can do to fix it. Thanks for the help @mackthehobbit
