### ISSUE TITLE
Needs to be updated to mcpe 0.14.0.3

### ISSUE THREAD

**Issue by CrazyWolfy23** [jv110/PocketRed#4]
Soon ill update to 0.14.0.3. Just give me some time.

**Comment by jv110** [comment]
But why? Redstone was already officially added in 0.13, and that was the only purpose of this mod

**Comment by jv110** [comment]
Unless you want this mod to include things PE doesn't include yet, which would be a lot easier because we don't have to create a whole Redstone system

**Comment by CrazyWolfy23** [comment]
When I said this, I didn't know about 0.14.0, so I think we should stop working on this

**Comment by CrazyWolfy23** [comment]
I had an idea to add more redstony stuff, kinda like ProjectRed from PC.

**Comment by mackthehobbit** [comment]
Perhaps start a new mod/project? This one is long dead.

**Comment by jv110** [comment]
@CrazyWolfy23 @mackthehobbit Yeah, let's do that, but I didn't mod since 0.11 so I'll need some headers

**Comment by CrazyWolfy23** [comment]
ill start on headers when 0.14.0 comes out officaly, unless you want to make the mod for 0.13.1

**Comment by CrazyWolfy23** [comment]
and whos going to be leader of the project

**Comment by jv110** [comment]
@CrazyWolfy23 Can it be me? Don't expect me to be *very* active though. I'm also working on plenty of other things.

**Comment by CrazyWolfy23** [comment]
@jv110 yes, as long as you give me collaborator ;)

**Comment by CrazyWolfy23** [comment]
what should we name it?

**Comment by jv110** [comment]
@CrazyWolfy23 "RedstonePlus", "Redstone+", "something like that" maybe?

**Comment by CrazyWolfy23** [comment]
"RedstonePlus" is good. Now what version are we makin it on? 0.13.1 or wait till 0.14.0

**Comment by jv110** [comment]
@CrazyWolfy23 0.14 beta, the headers won't change much

**Comment by CrazyWolfy23** [comment]
Ok, I'll start on headers soon. In the mean time, can you set up the pasic template of the addon.

**Comment by jv110** [comment]
@CrazyWolfy23 Fine.

**Comment by CrazyWolfy23** [comment]
I guess now we have to delete PocketRed.
